services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bin/dev"
    tty: true
    env_file: ./.env
    volumes:
      - ./:/app/:rw,delegated
      - bundle_data:/bundle
      - node_data:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    extra_hosts:
        knowledgebase: host-gateway
  db:
    image: postgres:14.13
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    command: postgres -c 'max_connections=250'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    volumes:
      - redis_data:/data
volumes:
  bundle_data:
  node_data:
  postgres_data:
  redis_data:
