default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PGHOST") { "db" } %>
  username: postgres
  password: <%= ENV["PGPASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: catholichighschoolchicago_development

test:
  <<: *default
  database: catholichighschoolchicago_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
